# Services
services:

  # Nginx Service
  ddc-app:
    container_name: ddc-app
    image: opeoniye/nginx-php-fpm:2.1.2
    restart: always
    environment:
      #SSH_KEY: $SSH_KEY
      # GIT_REPO: $GIT_REPO
      # GIT_EMAIL: $GIT_EMAIL
      # GIT_USERNAME: $GIT_USERNAME
      # GIT_NAME: $GIT_NAME
      # GIT_PERSONAL_TOKEN: $GIT_PERSONAL_TOKEN
      SKIP_COMPOSER: $SKIP_COMPOSER
    ports:
      - 1000:80
      - 4000:443
    networks:
      - bams
    volumes:
      - .:/var/www/html
      - ../../ops/docker/nginx/ddc.dev.conf:/etc/nginx/sites-available/default.conf
      - ../../ops/docker/nginx/proxy:/etc/nginx/proxy_params
      - ../../ops/docker/nginx/ssl.conf:/etc/nginx/ssl.conf
      - ~/dev/keys/mac:/var/keys/mac

networks:
  bams:
    name: bams
    external: true