# Services
services:

  # Nginx Service
  dclm-devs:
    container_name: dclm-devs
    image: opeoniye/nginx-php-fpm
    environment:
      GIT_REPO: ${GIT_REPO}
      GIT_EMAIL: ${GIT_EMAIL}
      GIT_NAME: ${GIT_NAME}
      GIT_BRANCH: ${GIT_BRANCH}
      GIT_PERSONAL_TOKEN: ${GIT_PERSONAL_TOKEN}
      WEBROOT: ${WEBROOT}
    ports:
      - 1000:80
    networks:
      - bams
    # volumes:
    #   - .:/var/www/developers
    #   - ./.docker/nginx/ddc.conf:/etc/nginx/conf.d/default.conf
    restart: always

networks:
  bams:
    name: bams-dev
    external: true