# Services
services:

  # Nginx Service
  nginx1.21:
    container_name: ddc-app
    image: opeoniye/nginx-php-fpm
    environment:
      GIT_REPO: ${GIT_REPO}
      GIT_EMAIL: ${GIT_EMAIL}
      GIT_NAME: ${GIT_NAME}
      GIT_BRANCH: ${GIT_BRANCH}
      GIT_PERSONAL_TOKEN: ${GIT_PERSONAL_TOKEN}
      WEBROOT: ${WEBROOT}
    ports:
      - 1000:80
    networks:
      - ddc_app
    # volumes:
    #   - .:/var/www/developers
    #   - ./.docker/nginx/ddc.conf:/etc/nginx/conf.d/default.conf
    restart: always

networks:
  ddc:
    name: ddc_app