services:

  ddc.nginx:
    container_name: nginx1.21
    image: opeoniye/nginx:1.21
    ports:
      - 1000:80
      - 4443:443
    volumes:
      - .:/var/www
      - ./.docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./.docker/nginx/testify.conf:/etc/nginx/conf.d/testify.conf
      - ./.docker/nginx/ssl.conf:/etc/nginx/ssl.conf
      - /etc/letsencrypt/live/dclm.org:/var/keys/dclm.org
    restart: always